CREATE OR REPLACE TABLE RAW.USERS (
  USER_ID NUMBER,
  SIGNUP_TS TIMESTAMP_NTZ,
  ACQUISITION_CHANNEL STRING,
  COUNTRY STRING,
  PLAN_TIER STRING,
  COMPANY_SIZE STRING
);

CREATE OR REPLACE TABLE RAW.EVENTS (
  EVENT_ID NUMBER,
  USER_ID NUMBER,
  EVENT_TS TIMESTAMP_NTZ,
  EVENT_TYPE STRING,
  FEATURE_NAME STRING,
  EXPERIMENT_NAME STRING,
  EXPERIMENT_VARIANT STRING,
  SESSION_DURATION_SEC NUMBER
);

CREATE OR REPLACE TABLE RAW.PAYMENTS (
  PAYMENT_ID NUMBER,
  USER_ID NUMBER,
  PAYMENT_TS TIMESTAMP_NTZ,
  AMOUNT_USD NUMBER(12,2),
  PAYMENT_STATUS STRING,
  INVOICE_TYPE STRING
);

CREATE OR REPLACE TABLE RAW.SUPPORT_TICKETS (
  TICKET_ID NUMBER,
  USER_ID NUMBER,
  CREATED_TS TIMESTAMP_NTZ,
  RESOLVED_TS TIMESTAMP_NTZ,
  SEVERITY STRING,
  CSAT_SCORE NUMBER
);
