CREATE OR REPLACE TABLE STAGING.USERS AS
SELECT
  USER_ID::NUMBER AS USER_ID,
  SIGNUP_TS::TIMESTAMP_NTZ AS SIGNUP_TS,
  ACQUISITION_CHANNEL,
  COUNTRY,
  PLAN_TIER,
  COMPANY_SIZE
FROM RAW.USERS
WHERE USER_ID IS NOT NULL;

CREATE OR REPLACE TABLE STAGING.EVENTS AS
SELECT
  EVENT_ID::NUMBER AS EVENT_ID,
  USER_ID::NUMBER AS USER_ID,
  EVENT_TS::TIMESTAMP_NTZ AS EVENT_TS,
  EVENT_TYPE,
  FEATURE_NAME,
  EXPERIMENT_NAME,
  EXPERIMENT_VARIANT,
  SESSION_DURATION_SEC::NUMBER AS SESSION_DURATION_SEC
FROM RAW.EVENTS
WHERE USER_ID IS NOT NULL;

CREATE OR REPLACE TABLE STAGING.PAYMENTS AS
SELECT
  PAYMENT_ID::NUMBER AS PAYMENT_ID,
  USER_ID::NUMBER AS USER_ID,
  PAYMENT_TS::TIMESTAMP_NTZ AS PAYMENT_TS,
  AMOUNT_USD::NUMBER(12,2) AS AMOUNT_USD,
  PAYMENT_STATUS,
  INVOICE_TYPE
FROM RAW.PAYMENTS
WHERE USER_ID IS NOT NULL;

CREATE OR REPLACE TABLE STAGING.SUPPORT_TICKETS AS
SELECT
  TICKET_ID::NUMBER AS TICKET_ID,
  USER_ID::NUMBER AS USER_ID,
  CREATED_TS::TIMESTAMP_NTZ AS CREATED_TS,
  RESOLVED_TS::TIMESTAMP_NTZ AS RESOLVED_TS,
  SEVERITY,
  CSAT_SCORE::NUMBER AS CSAT_SCORE
FROM RAW.SUPPORT_TICKETS
WHERE USER_ID IS NOT NULL;
