CREATE OR REPLACE TABLE MARTS.DAILY_KPIS AS
WITH signups AS (
  SELECT DATE_TRUNC('DAY', SIGNUP_TS)::DATE AS METRIC_DATE, COUNT(*) AS NEW_USERS
  FROM STAGING.USERS
  GROUP BY 1
),
active_users AS (
  SELECT DATE_TRUNC('DAY', EVENT_TS)::DATE AS METRIC_DATE, COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
  FROM STAGING.EVENTS
  WHERE EVENT_TYPE = 'session_start'
  GROUP BY 1
),
conversions AS (
  SELECT DATE_TRUNC('DAY', EVENT_TS)::DATE AS METRIC_DATE, COUNT(DISTINCT USER_ID) AS PAID_CONVERSIONS
  FROM STAGING.EVENTS
  WHERE EVENT_TYPE = 'subscription_started'
  GROUP BY 1
),
revenue AS (
  SELECT
    DATE_TRUNC('DAY', PAYMENT_TS)::DATE AS METRIC_DATE,
    SUM(IFF(PAYMENT_STATUS='success', AMOUNT_USD, 0)) AS GROSS_REVENUE_USD,
    SUM(IFF(PAYMENT_STATUS='refund', AMOUNT_USD, 0)) AS REFUNDED_USD
  FROM STAGING.PAYMENTS
  GROUP BY 1
)
SELECT
  d.METRIC_DATE,
  COALESCE(s.NEW_USERS, 0) AS NEW_USERS,
  COALESCE(a.ACTIVE_USERS, 0) AS ACTIVE_USERS,
  COALESCE(c.PAID_CONVERSIONS, 0) AS PAID_CONVERSIONS,
  COALESCE(r.GROSS_REVENUE_USD, 0) AS GROSS_REVENUE_USD,
  COALESCE(r.REFUNDED_USD, 0) AS REFUNDED_USD,
  COALESCE(r.GROSS_REVENUE_USD, 0) - COALESCE(r.REFUNDED_USD, 0) AS NET_REVENUE_USD,
  IFF(COALESCE(s.NEW_USERS, 0)=0, 0, COALESCE(c.PAID_CONVERSIONS, 0)/s.NEW_USERS::FLOAT) AS CONVERSION_RATE,
  IFF(COALESCE(r.GROSS_REVENUE_USD, 0)=0, 0, COALESCE(r.REFUNDED_USD, 0)/r.GROSS_REVENUE_USD::FLOAT) AS REFUND_RATE
FROM (
  SELECT METRIC_DATE FROM signups
  UNION SELECT METRIC_DATE FROM active_users
  UNION SELECT METRIC_DATE FROM conversions
  UNION SELECT METRIC_DATE FROM revenue
) d
LEFT JOIN signups s USING (METRIC_DATE)
LEFT JOIN active_users a USING (METRIC_DATE)
LEFT JOIN conversions c USING (METRIC_DATE)
LEFT JOIN revenue r USING (METRIC_DATE)
ORDER BY METRIC_DATE;
